### PR TITLE
Add support for PYNQ Bootcamp 2021 sensors 

### PR DESCRIPTION
**Pull request by vikhyatg**
Add support for:
- Grove Barometric Sensor
- Sparkfun Environment Sensor (BME680)

### CODE REVIEW

**Comment by npurusho** [comment]
Hi @vikhyatg 
Thanks for the pull request. It looks good Can you please add comments in the .h files similar to other peripherals with the same syntax for your functions (atleast the essential ones). These comments will be pulled up as docstrings in ipynb in jupyter.
I will merge this asap.

**Comment by vikhyatg** [comment]
Hello Naveen,  I have added the function description for both sensors with https://github.com/Xilinx/PYNQ_peripherals/pull/2/commits/c3f7785c338875a1082e88f1b0d5dfb714f5dec5

Let me know if any other clean-up is required.
Thanks

**Comment by npurusho** [comment]
Thanks Anurag. I merged it.

**Comment by vikhyatg** [comment]
You mean Vikhyat :P
Thanks for merging!

**Pull request merged**
